### ISSUE TITLE
import error: ctranxn

### ISSUE THREAD

**Issue by boblannon** [libindic/indic-trans#18]
### Context

Python 2.7 (also re-created with 3.5)
Darwin Kernel Version 15.6.0
macosx-10.11-x86_64

installed packages (after following installation steps):

```
$ pip freeze
Cython==0.24.1
future==0.15.2
indictrans==0.0.1.dev285
numpy==1.11.1
pbr==1.10.0
scipy==0.18.0
six==1.10.0
```

### What I did

Installed package by following steps in README.rst. Attempted two things:

```
$ indictrans --h
```

and

```
$ python
>>> from indictrans import Transliterator
```

### Expected behavior

A help message from the command line call and the ability to import within the python interpreter

### Actual behavior

Got `ImportError`.

Python 2.7 version: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "indictrans/__init__.py", line 9, in <module>
    from ._utils import UrduNormalizer, WX
  File "indictrans/_utils/__init__.py", line 6, in <module>
    from .ctranxn import count_tranxn
ImportError: No module named ctranxn
```

Python 3.5: 

```
Traceback (most recent call last):
  File "/Users/bob/src/indic-trans/env/bin/indictrans", line 6, in <module>
    from indictrans import main
  File "/Users/bob/src/indic-trans/indictrans/__init__.py", line 9, in <module>
    from ._utils import UrduNormalizer, WX
  File "/Users/bob/src/indic-trans/indictrans/_utils/__init__.py", line 6, in <module>
    from .ctranxn import count_tranxn
ImportError: No module named 'indictrans._utils.ctranxn'
```

I'm also attaching the full backscroll of the compilation, etc, for more info.
[indictrans_console.txt](https://github.com/libindic/indic-trans/files/474838/indictrans_console.txt)

**Comment by irshadbhat** [comment]
All you need to do is to come out of the source-code directory. You are calling a local import there. The module is loaded from the source-code directory itself. Since, you haven't build the Cython files in-place, the local source-code directory does not have the **.so** files which causes ImportError for ``ctrans`` and for other Cython files. If you come out of the source-code directory the module will be imported from the installed location and will work fine. 

If you want the package to work from the source-code directory as well or to use the package from its source directory without installing, you need to build the Cython files inplace as:

`python setup.py build_ext --inplace`

**Comment by boblannon** [comment]
ahhhhh, i see.  yep, that took care of it.  thanks!

**Comment by AfrahAsif** [comment]
> 
> 
> All you need to do is to come out of the source-code directory. You are calling a local import there. The module is loaded from the source-code directory itself. Since, you haven't build the Cython files in-place, the local source-code directory does not have the **.so** files which causes ImportError for `ctrans` and for other Cython files. If you come out of the source-code directory the module will be imported from the installed location and will work fine.
> 
> If you want the package to work from the source-code directory as well or to use the package from its source directory without installing, you need to build the Cython files inplace as:
> 
> ```
> python setup.py build_ext --inplace
> ```

could you explain in a easier way...I have the same error

**Comment by irshadbhat** [comment]
Either change your `current working directory` to some directory other than `indic-trans` or run the command `python setup.py build_ext --inplace`.

**Comment by swapnil3597** [comment]
Once installing `requirements.txt`

While you are in `indic-trans/` dir perform `cd ..` to go once directly back and run below command:

```bash
pip install indic-trans/
```

**Comment by SabaAnjum2002** [comment]
After moving out of the source directory also I am facing the  issue .I was in indic-trans directory when I faced this issue and as you told to come out of source directory I came out using cd.. command .and used python -i command to open python editor and ran the same import satatement.Then too getting the same issue.

> > All you need to do is to come out of the source-code directory. You are calling a local import there. The module is loaded from the source-code directory itself. Since, you haven't build the Cython files in-place, the local source-code directory does not have the **.so** files which causes ImportError for `ctrans` and for other Cython files. If you come out of the source-code directory the module will be imported from the installed location and will work fine.
> > If you want the package to work from the source-code directory as well or to use the package from its source directory without installing, you need to build the Cython files inplace as:
> > ```
> > python setup.py build_ext --inplace
> > ```
> 
> could you explain in a easier way...I have the same error



> All you need to do is to come out of the source-code directory. You are calling a local import there. The module is loaded from the source-code directory itself. Since, you haven't build the Cython files in-place, the local source-code directory does not have the **.so** files which causes ImportError for `ctrans` and for other Cython files. If you come out of the source-code directory the module will be imported from the installed location and will work fine.
> 
> If you want the package to work from the source-code directory as well or to use the package from its source directory without installing, you need to build the Cython files inplace as:
> 
> ```
> python setup.py build_ext --inplace
> ```
I am getting the same after doing this.As you told to move out of source directory  I did cd .. to move out of the directory .Then used python -i command to write python command .and wrote(from indictrans import Transliterator) command then also facing same issue
