### ISSUE TITLE
Problem in Hindi to English Translation.

### ISSUE THREAD

**Issue by maheshuligade** [libindic/indic-trans#19]
की  translate should be kee not kii.

की should translate to  "kee" but it gives "kii"
(means "of")
कि  should translate to  "ki" 
(means "such that")

**Comment by maheshuligade** [comment]
I fixed the Issue. check at
https://github.com/libindic/Transliteration/pull/12

**Comment by copyninja** [comment]
indic-trans and Transliteration are 2 different repository and they work differently also. Which repository did you try?. If you tried with Transliteration project (as suggested by linked pull request) I request you to open issue there and not here.
