### ISSUE TITLE
ImportError: No module named ctranxn

### ISSUE THREAD

**Issue by rollingsun** [libindic/indic-trans#22]
When I am trying to import Transliterator from indictrans I am getting this error

> >>> from indictrans import Transliterator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "indictrans/__init__.py", line 9, in <module>
    from ._utils import UrduNormalizer, WX
  File "indictrans/_utils/__init__.py", line 6, in <module>
    from .ctranxn import count_tranxn
ImportError: No module named ctranxn

**Comment by rollingsun** [comment]
Issue was resolved by adding following code in _utils/__init__.py
>import pyximport
pyximport.install()

**Comment by irshadbhat** [comment]
You don't need to add anything to _utils/init.py. All you need is to move out of the source code directory after successful installation of the package. See #18

**Comment by soumendrak** [comment]
I confirm moving out of the source code directory fixed this issue. It should be closed.

**Comment by Deepthi-Chand** [comment]
@irshadbhat You might want to close this issue
