### ISSUE TITLE
Urdu to English transliteration not implemented?

### ISSUE THREAD

**Issue by e-matusov** [libindic/indic-trans#33]
Hi, thank you for your work!
Running this command 
`indictrans --s urd --t eng --build-lookup`
resulted in:
`NotImplementedError: Language "eng" is not implemented.`

So is Urdu to English transliteration not implemented? I tried transliterating from Hindi to English, it worked.

**Comment by irshadbhat** [comment]
Urdu to English transliteration is already implemented.
Can you send me a screenshot.

**Comment by irshadbhat** [comment]
Thanks for pointing out. This is a minor bug. Will fix it asap.

**Comment by tc9sachin12** [comment]
This problem still exists!!

**Comment by tc9sachin12** [comment]
Screenshot of the problem:
![Screenshot from 2019-12-04 15-23-53](https://user-images.githubusercontent.com/57592924/70132475-51274180-16aa-11ea-96da-170f5ca851fc.png)
![Screenshot from 2019-12-04 15-24-46](https://user-images.githubusercontent.com/57592924/70132493-5edcc700-16aa-11ea-8bba-7d725e984412.png)

**Comment by tc9sachin12** [comment]
If i change the build_lookup to "False" , then it works as pointed out earlier.

**Comment by irshadbhat** [comment]
I fixed this issue when it was raised and sent a pull request. For some reason the pull request has not been merged yet.

I build this library as a [GSoC](https://summerofcode.withgoogle.com/archive/)  project for libindic. Though I am the only contributor, I don't have write access to libindic. So, I can't change the code directly.

You can get the latest code from [irshadbhat/indic-trans](https://github.com/irshadbhat/indic-trans).

**Comment by tc9sachin12** [comment]
@irshadbhat : Thank you. :)

**Comment by jishnu7** [comment]
@irshadbhat is there a PR for this? I can help in merging it.

**Comment by irshadbhat** [comment]
@jishnu7 Yes, there is only one PR right now and it is for this issue (#33) and another one raised recently (#34). I have fixed both these issues and sent a PR.

**Comment by jishnu7** [comment]
Merged
