### ISSUE TITLE
[QUESTION] How get the exact length of Hindi text without Mark, Nonspacing

### ISSUE THREAD

**Issue by loretoparisi** [libindic/indic-trans#37]
In my source indic text (like Hindi) I'm dealing with text tokenization. I'm currently using the https://github.com/irshadbhat/polyglot-tokenizer for this task. By the way I came across the problem of the non Unicode characters in the Mark, Nonspacing (Mn) Category - https://www.fileformat.info/info/unicode/category/Mn/list.htm, and I wonder if libindic is handling this internally in some way.
This was my approach: https://stackoverflow.com/questions/54345897/fastest-way-to-count-non-spacing-chars-in-unicode-text-in-python

Thank you.

**Comment by irshadbhat** [comment]
What exactly do you mean by handling this internally. Do  you mean skipping these characters from transliterating or something else. What exactly is the issue. Can you explain with an example.

**Comment by loretoparisi** [comment]
@irshadbhat Basically since `अब यहां से कहा जाएँ हम".length` gives 22, but the visible characters are actually 16, I would like to have a function to count these ones, excluding the characters belonging to the Mn Category above.

[This](https://stackoverflow.com/a/54358186/758836) the last pythonic implementation:

```python
import sys
from unicodedata import category

MARK_SET = set(chr(c) for c in range(sys.maxunicode + 1) if category(chr(c))[0] == 'M')

s = "अब यहां से कहा जाएँ हम"

def count_len(s):
    return len([c for c in s if c not in MARK_SET])

if __name__ == '__main__':
    print(len(s))
    print(count_len(s))
```

**Comment by loretoparisi** [comment]
@irshadbhat yes you are right, I was thinking to add this feature while tokenizing and transliterating, and my wonder was if this has been addressed here before! thanks.
