### ISSUE TITLE
About Sanskrit and Hindi

### ISSUE THREAD

**Issue by loretoparisi** [libindic/indic-trans#39]
In my findings, the `hin-eng` model is capable to transliterate input text in indian Sanskrit even if the selected model used was `hin` (Hindi). This of course does not happen when the input text is let's say `urd` or `pan`. Can we say therefore that there are similarities among **Sanskrit** and **Devanagari**, so the model is transcribing it anyways?

Like in the following cases

| text        | transliteration          
| ------------- |:-------------:|
| षट्त्रिंशकात्मकजगद्गगनावभास-|shattrinshkatmakajgadgaganavbhas-
संविन्मरीचिचयचुम्बितबिम्बशोभम्|sanvinmarichichaychumbitbimbashobham
षट्त्रिंशकं भरतसूत्रमिदं विवृण्व-|shattrinshakan bharatsutramidan vivrunv-
न्वन्दे शिवं श्रुतितदर्थविवेकधाम |nvande shivan shrutitadarthvivekdham

or 

| text        | transliteration          
| ------------- |:-------------:|
|यदेतत्कालिन्दी-तनुतर-तरङ्गाकृति शिवे| yadetatkalindi-tanutar-tarangakriti shive
|कृशे मध्ये किञ्चिज्जननि तव यद्भाति सुधियाम्| krishe madhye kinchijjanani tav yadbhaati sudhiyam
|विमर्दा-दन्योन्यं कुचकलशयो-रन्तरगतं| vimarda-danyonyan kuchkalashyo-rantaragatan
|तनूभूतं व्योम प्रविशदिव नाभिं कुहरिणीम्| tanubhutan vyom pravishadiv naabhin kuharinim
|स्थिरो गङ्गा वर्तः स्तनमुकुल-रोमावलि-लता| sthiro ganga vartah stanmukul-romavali-lata
|कलावालं कुण्डं कुसुमशर तेजो-हुतभुजः| kalavalan kundan kusumshar tejo-hutbhujah
|रते-र्लीलागारं किमपि तव नाभिर्गिरिसुते| rate-rlilagaaran kimapi tav nabhirgirisute

Thank you.

**Comment by irshadbhat** [comment]
Can we say therefore that there are similarities among Sanskrit and Devanagari?

Sanskrit is a language, where as, Devanagari is a script. Both Hindi and Sanskrit use the same script Devanagari, that is why the Hindi model is able to transliterate Sanskrit.

**Comment by loretoparisi** [comment]
@irshadbhat you are totally right. Closing, thank you very much, my knowledge of languages today changed completely its point of view 👍
