### ISSUE TITLE
Tests fail in python3 due to use of unichr

### ISSUE THREAD

**Issue by copyninja** [libindic/indic-trans#4]
unichr is only available only for python2 in python3 equivalent is chr. Please fix the tests.

**Comment by irshadbhat** [comment]
To make it compatible with python3 many fixes are required (mostly unicode). I'll come up with python3 compatibility very shortly.

**Comment by copyninja** [comment]
Alright. I added this as tracking issue of python3 support.

**Comment by irshadbhat** [comment]
I guess we can close this issue now as I have updated the codes to support both python 2 and 3.

**Comment by copyninja** [comment]
Thanks closing it.
