### ISSUE TITLE
Tamil transliterator puts 'm' as 's'

### ISSUE THREAD

**Issue by warnak** [libindic/indic-trans#40]
Steps to reproduce the issue: Find the file "tamtrial2out.txt" and use 

indictrans < <path>/tamtrial2out.txt --s tam --t eng --build-lookup > <path>/tamtrial2outrom.txt

you should get a "tamtrial2outrom.txt" and compare it with the attached file of the same name.

Issue: The 6th and the 2nd last token 'patus' is actually 'patum'.

[tamtrial2outrom.txt](https://github.com/libindic/indic-trans/files/3054030/tamtrial2outrom.txt)
[tamtrial2out.txt](https://github.com/libindic/indic-trans/files/3054031/tamtrial2out.txt)

**Comment by irshadbhat** [comment]
The accuracy of a machine learning (ML) model depends on the amount and quality of data and the complexity of the task in hand. Given all the transliteration models of this repository are ML models, these models cannot be 100% accurate.
