### ISSUE TITLE
Throws multiple Traceback errors

### ISSUE THREAD

**Issue by ShakesVision** [libindic/indic-trans#42]
I installed everything as mentioned and all went well without any problem. Though, when implementing, it throws these errors: (Screenshot)

![indictrans error](https://user-images.githubusercontent.com/10809552/68362187-57c6a580-014c-11ea-9835-d0ef910e1798.JPG)

I'm trying to transliterate this [Urdu word-list](http://kitaben.urdulibrary.org/urdu_in.dic) into roman(English). If possible, please upload it somewhere if you get it converted successfully, or any other list if you have.

I think you should also add all useful word-list files you've converted successfully in this/other repo.

**Comment by irshadbhat** [comment]
Could you try with `python2.7`. I think there is some incompatibility between the model pickle files for python 2 and 3.
