### ISSUE TITLE
Is Hindi-Urdu transliteration lossless?

### ISSUE THREAD

**Issue by GokulNC** [libindic/indic-trans#52]
First of all, thanks a lot for this repo!
It's very useful.

Just wanted to know if the PersoArabic to Devanagari transliteration is lossless.
That is, will `Urdu->Hindi->Urdu` or `Hindi->Urdu->Hindi` always retain all the same original characters?

Also, is Urdu only rule-based available?
@irshadbhat

**Comment by irshadbhat** [comment]
No hin-urd-hin is not lossless. 

Urdu has trained models as well like other scripts.

**Comment by GokulNC** [comment]
Thank you 👍
