### ISSUE TITLE
How one can improvise urd to eng transliteration

### ISSUE THREAD

**Issue by asifkhan69** [libindic/indic-trans#60]
Using indic-trans module for transliteration of urd to eng is not 99% correct example I passed
urd='''محمد حفیظ پاکستانی کرکٹ ٹیم کے لیے مزید کھیلنا چاہتے تھے: شاہد آفرید''' and gives transliterate into english '''mohammad hafiz pakistani crookat tem ke liye majid khelnaa chahate the: shahid afaredi''' which is not correct 99% it should be "Muhammad Hafeez pakistani cricket team key liye mazeed khalna chahatey thay: shahid afridi" 

Is there a way we can our own improvise mapping.? or what is your advice.

**Comment by irshadbhat** [comment]
Where do we report its 99% correct? 

If you want to improve the system,find more training data and retrain the model. Training procedure is given [here](https://indic-trans.readthedocs.io/en/latest/guide_model.html)
