### ISSUE TITLE
URDU To ENGLISH Transliteration mapping issue

### ISSUE THREAD

**Issue by asifkhan69** [libindic/indic-trans#61]
I have tested and found some mapping problem for urdu to english here is an example
if give  مزید it convert as "MAJID" where as it should covert as "MAZEED". I have check individual character "ذ" or "ز" is giving correct mapping as "Z" "ZA"

Please look into it or advice what I can do for correct conversion.

**Comment by irshadbhat** [comment]
Both Majid and Majeed are equally valid as there is no standard spelling when we romanize Urdu.

**Comment by asifkhan69** [comment]
thanks for your response. No I mentioned "Mazeed" not "Majeed". Majeed and Mazeed is completely different. I would appreciate if you provide sample file for model training so I can try my model.
